.\"<!-- Copyright 2002-2010 Double Precision, Inc.  See COPYING for -->
.\"<!-- distribution information. -->
'\" t
.\"     Title: leaf
.\"    Author: Sam Varshavchik
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 04/04/2011
.\"    Manual: Cone: COnsole Newsreader And Emailer
.\"    Source: 
	Cone\(co
      
.\"  Language: English
.\"
.TH "LEAF" "1" "04/04/2011" "Cone\(co" "Cone: COnsole Newsreader And E"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
leaf \- Lightweight Editor of Ascii(and more) Files
.SH "SYNOPSIS"
.HP \w'\fBleaf\fR\ 'u
\fBleaf\fR [\-f] [\-d\ \fIdictionary\fR] [+\fIn\fR] [\fIfilename\fR]
.SH "USAGE"
.PP

\fBleaf\fR
is a simple console text file editor, with paragraph word\-wrapping and spell checking\&.
\fBleaf\fR
is based on the text editor in the
Cone
mail reader and composer\&.
\fBleaf\fR
opens
\fIfilename\fR, positioning the cursor on the first line, or line #\fIn\fR, if specified\&.
.PP
This is not really the best editor for program sources\&.
\fBleaf\fR
is meant to be used as a quick editor for writing short notes and memos\&. As text is typed, words will automatically flow to wrap within a typical 80\-character terminal display, even on larger display (due to
\fBleaf\fR\'s heritage as an editor for E\-mail messages, which are traditionally formatted to fit an 80\-character display)\&. Word wrapping is "lazy": only long text lines are wrapped\&. Short text lines are not folded together\&. Individual paragraphs are separated by blank lines of text\&. Press
CTRL\-J
to optimally rejustify the paragraph under the cursor\&. The bottom two lines on the screen list which keys to press for other functions\&.
.SS "Flowed text"
.PP
The
\fB\-f\fR
option enables
\(lqflowed text\(rq
formatting convention\&. Plain text files have no explicit means for joining multiple lines into logical paragraph\&. Each line of text is an individual line, and a blank line marks the end of a paragraph\&.
.PP
In a
\(lqflowed text\(rq
formatted file, each line in a paragraph except the last one ends with a space character\&. This makes no visual difference, it\'s just a marker that this line should be merged with the next line\&. The last line in the paragraph does not end in a space character\&.
.PP
The trailing space character is logically removed from each flowed line, and all flowed lines are merged into a logical paragraph that can be adjusted to any display width\&. It\'s important to note that text written in non\-ideographic languages, where individual words are separated by spaces, will have two space characters at the end of every line: the space character that separates the last word on the line from the first word on the next line, and the a second space character that marks the line as a flowed line\&.
.PP
Because the trailing space marking a flowed line is logically removed, without the second space character there will not be a logical space between the two words, and if the paragraph\'s width is adjusted for display the two words may get combined together\&.
.PP
The
\fB\-f\fR
option puts
\fBleaf\fR
into flowed text mode, removing spaces from each flowed line of text in an opened file\&. A flowed line is marked on the screen with a "<" character in the right margin (or a small "next line" character on a UTF\-8 display)\&. When saving a file
\fBleaf\fR
automatically adds a trailing space to each line that\'s marked as flowed\&.
.PP
The flowed text mode stays in effect for each file opened in
\fBleaf\fR\&. When opening another file, press
CTRL\-F
to turn flowed mode on or off for the next file\&. This change stays in effect until it gets toggled again\&.
.PP
Pressing
CTRL\-J
optimally rejustifies the text in flowed text mode\&.
\fBleaf\fR
heuristically determines the start and the end of the paragraph, readjusts the width of the paragraph, and marks each line as flowed, except the last paragraph line\&.
\fBleaf\fR
uses a unicode\-based algorithm for determining whether the last character line needs a space character, in addition to the flowed space marker\&.
.if n \{\
.sp
.\}
.RS 4
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
.ps +1
\fBNote\fR
.ps -1
.br
.PP

\fBleaf\fR
is frequently used to edit plain text email message content\&. Because email messages assign some semantical meaning to lines of text that start with spaces or ">" characters,
CTRL\-J
will not rejustify lines of text that begin with a ">" or a space\&. These lines will be considered paragraph boundaries, in addition to blank lines\&.
.sp .5v
.RE
.SS "Spell checking"
.PP
The
\fB\-d\fR
option sets the name of the dictionary used for spell checking (overriding the default spell checking dictionary set by the
\fBDICTIONARY\fR
environment variable)\&.
\fB+\fR\fB\fIn\fR\fR
sets the initial cursor position to line #\fIn\fR\&.
.SH "SEE ALSO"
.PP

\fBemacs\fR(1),
\fBvi\fR(1)
.SH "AUTHOR"
.PP
\fBSam Varshavchik\fR
.RS 4
.RE
