.\"<!-- $Id: book.sgml,v 1.4 2007/04/05 02:35:33 mrsam Exp $ -->
.\"<!-- Copyright 2002-2003 Double Precision, Inc.  See COPYING for -->
.\"<!-- distribution information. -->
'\" t
.\"     Title: mailtool
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 05/08/2010
.\"    Manual: Cone: COnsole Newsreader And Emailer
.\"    Source: [FIXME: source]
.\"  Language: English
.\"
.TH "MAILTOOL" "1" "05/08/2010" "[FIXME: source]" "Cone: COnsole Newsreader And E"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
mailtool \- Process mailboxes
.SH "SYNOPSIS"
.HP \w'\fBmailtool\fR\ 'u
\fBmailtool\fR [options...]
.SH "USAGE"
.PP

\fBmailtool\fR
is a diagnostic utility for handling various operations on mailboxes\&.
\fBmailtool\fR\'s main uses include: display the list of folders in a mailbox; displaying list of messages in a mailbox; and copying mailboxes\&.
.PP
The following mailboxes can be accessed by
\fBmailtool\fR:
.PP
imap://\fIuserid\fR@\fIserver\fR[/options]
.RS 4
An IMAP account\&.
\fBmailtool\fR
will prompt for the login password\&.
.RE
.PP
imaps://\fIuserid\fR@\fIserver\fR[/options]
.RS 4
An IMAP account accessed via an encrypted SSL connection\&.
.RE
.PP
pop3://\fIuserid\fR@\fIserver\fR[/options]
.RS 4
A POP3 account\&.
\fBmailtool\fR
will prompt for the login password\&.
.RE
.PP
pop3s://\fIuserid\fR@\fIserver\fR[/options]
.RS 4
A POP3 account accessed via an encrypted SSL connection\&.
.RE
.PP
maildir:\fIpath\fR
.RS 4
A local maildir mailbox\&.
path
specifies the maildir\'s location relative to the home directory (NOT the current directory)\&.
.RE
.PP
mbox:\fIpath\fR
.RS 4
Local mbox mail folders\&.
path
specifies the path to an mbox folder file, or a directory containing mbox folders, relative to the home directory (NOT the current directory)\&.
.RE
.PP
inbox:\fIpath\fR
.RS 4
Local mbox mail folders, like
\(lqmbox:\fIpath\fR\(rq; additionally, the system spool mailbox is automatically copied to
$HOME/Inbox, which is accessible as folder
INBOX\&.
.RE
.PP
The name of a remote IMAP or POP3 server may be followed by one or more options that control various settings of the IMAP or POP3 connection:
.PP
/cram
.RS 4
Do not open the account unless the server supports secure password authentication\&. Secure password authentication verifies the account\'s password using a challenge/response authentication mechanism (where the label "cram" comes from)\&. The actual password is never actually transmitted to the server, and therefore cannot be intercepted while in transit over an untrusted network\&.
.sp
Secure password authentication is not supported by all servers\&. This option may not work with some servers\&. This option does not enable secure password authentication, it only mandates its use\&. If the server supports secure password authentication, it will be used even without the
/cram
option\&. Traditional userid/password authentication will be used only if the server does not implement secure password authentication\&. The
/cram
option makes secure password authentication mandatory\&.
.sp
The
/cram
option is marginally useful even with encrypted server connections\&. The secure password authentication never sends the explicit password to the server\&. Encryption makes it theoretically impossible to recover the password from an encrypted data connection; but with secure authentication the password is never sent over the connection in the first place (the password\'s validity is certified by exchanging certain mathematical calculations between the server and the client)\&. If the server is compromised, the compromised server will not receive the account password (unless the password is recovered from the server in other ways)\&.
.RE
.PP
/imap
.RS 4
Do not use the
SMAP
if the server claims the availability of this experimental mail access protocol, and fall back to IMAP compatibility mode (this option is meaningful only with
\(lqimap://\(rq
and
\(lqimaps://\(rq
URLs)\&.
.RE
.PP
/notls
.RS 4
Do not upgrade a plain connection to an encrypted one\&. This option is primarily used for testing and debugging purposes\&. Sometimes this option might be useful with servers that claim to offer encryption, but are unable to do so when taken up on their offer\&.
.RE
.PP
/novalidate\-cert
.RS 4
Do not validate the server\'s SSL certificate when using an encrypted connection\&. Normally the mail server\'s SSL certificate must be validate when using an encrypted connection\&. The certificate\'s name must match the server\'s name, and the certificate must be signed by a trusted certificate authority\&.
.sp
The encrypted connection normally fails if the certificate cannot be validate\&. Validation requires that a list of trusted certificate authorities must be known and configured\&. It\'s simply impossible to know which certificate authorities are valid without an explicit list of valid, known, trusted, certificate authorities\&. If a trusted authority list is not configured, no certificate can be validated\&. If the server\'s certificate is a self\-signed certificate (this is often used for testing purposes), or if it\'s not signed by a known authority, the encrypted connection fails\&.
.sp
This
/novalidate\-cert
option disables certificate validation\&. The encrypted connection will be established even if the server\'s certificate would otherwise be rejected\&.
.if n \{\
.sp
.\}
.RS 4
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
.ps +1
\fBNote\fR
.ps -1
.br
This option is applicable even when an encrypted IMAP or POP3 connection is not explicitly requested\&. Many mail servers are capable of automatically upgrading unencrypted connections to a fully\-encrypted connection\&. If a mail server claims to be able to use encryption, then there\'s no reason not to use it\&. The result is that all encryption certification requirements still apply even when encryption is not explicitly requested\&.
.sp .5v
.RE
.RE
.SS "Displaying mailbox contents"
.HP \w'\fBmailtool\fR\ 'u
\fBmailtool\fR \-tree | \-list  \fIaccount\fR
.PP

\-tree
shows a hierarchical representation of mail folders in
\fIaccount\fR\&.
\-list
generates a simple folder listing, one folder name per line\&.
\-tree
shows folder names, while
\-list
shows the actual mail folder path in
\fIaccount\fR\&.
.sp
.if n \{\
.RS 4
.\}
.nf
mailtool \-tree imap://jsmith@mail\&.example\&.com/novalidate\-cert/cram
.fi
.if n \{\
.RE
.\}
.SS "Creating folders"
.HP \w'\fBmailtool\fR\ 'u
\fBmailtool\fR \-create | \-createdir  \fIfolder\fR \fIname\fR \fIaccount\fR
.PP

\-create
creates a new subfolder of
\fIfolder\fR
in
\fIaccount\fR\&. The new subfolder\'s name is
\fIname\fR\&.
\-createdir
creates a new folder directory (a folder that contains other folders)\&.
.sp
.if n \{\
.RS 4
.\}
.nf
mailtool \-create INBOX\&.lists announcements maildir:Maildir
.fi
.if n \{\
.RE
.\}
.PP
This command creates a new folder
\(lqannouncements\(rq
as a subfolders of
\(lqINBOX\&.lists\(rq
in the local maildir\&.
.SS "Deleting folders"
.HP \w'\fBmailtool\fR\ 'u
\fBmailtool\fR \-delete | \-deletedir  \fIfolder\fR \fIaccount\fR
.PP

\-delete
deletes an existing
\fIfolder\fR
in
\fIaccount\fR\&.
.PP

\-deletedir
deletes a folder directory\&.
.sp
.if n \{\
.RS 4
.\}
.nf
mailtool \-delete INBOX\&.lists\&.announcements maildir:Maildir
.fi
.if n \{\
.RE
.\}
.SS "Renaming folders"
.HP \w'\fBmailtool\fR\ 'u
\fBmailtool\fR \-rename \fIoldfolder\fR \fIfolder\fR \fIname\fR \fIaccount\fR
.PP

\-renames
renames an existing
\fIoldfolder\fR\&. The folder is renamed as
\fIname\fR, as a subfolder of
\fIfolder\fR\&.
\fIfolder\fR
may be an empty string if the folder should be moved to the top level of
\fIaccount\fR\'s folder hierarchy\&.
.sp
.if n \{\
.RS 4
.\}
.nf
mailtool \-rename INBOX\&.lists\&.announcements INBOX\&.lists Announcements maildir:Maildir
.fi
.if n \{\
.RE
.\}
.PP
The folder
\(lqINBOX\&.lists\&.announcements\(rq
is renamed to
\(lqINBOX\&.lists\&.Announcements\(rq\&. This slightly unusual way to rename folder allows folders to be relocated in the mail
\fIaccount\fR\'s folder hierarchy\&.
.SS "Reading folder\'s index"
.HP \w'\fBmailtool\fR\ 'u
\fBmailtool\fR \-index \fIfolder\fR \fIaccount\fR
.PP

\-index
downloads and prints a summary of all messages in
\fIfolder\fR, in
\fIaccount\fR\&. The summary shows the sender\'s and recipients\' address, the message\'s subject, and size\&.
.sp
.if n \{\
.RS 4
.\}
.nf
mailtool \-index INBOX imap://john@mail\&.example\&.com/novalidate\-cert
.fi
.if n \{\
.RE
.\}
.SS "Removing a message from a folder"
.HP \w'\fBmailtool\fR\ 'u
\fBmailtool\fR \-remove \fIfolder\fR \fIn\fR \fIaccount\fR
.PP

\-remove
removes message #\fIn\fR
(ranging from 1 to the number of messages in the folder) in
\fIfolder\fR, in
\fIaccount\fR\&. The message numbers may be obtained by using
\-index\&.
.PP

\fIn\fR
may be a comma\-separated list of message numbers, in strictly numerically increasing order\&.
\-remove
confirms the list of messages to remove and issues a
\(lqReady:\(rq
prompt\&. Press
ENTER
to remove the messages\&.
.sp
.if n \{\
.RS 4
.\}
.nf
mailtool \-remove INBOX 28,31 imap://john@mail\&.example\&.com/novalidate\-cert
.fi
.if n \{\
.RE
.\}
.SS "Filtering messages"
.HP \w'\fBmailtool\fR\ 'u
\fBmailtool\fR \-filter \fIfolder\fR \fIaccount\fR
.PP

\-filter
is a combination of
\-index
and
\-remove\&.
\fIfolder\fR\'s index is downloaded, and the summary of each message is shown, one message at a time\&. Each message\'s summary is followed by a prompt:
\(lqDelete, Skip, or Exit\(rq\&. Pressing
D
removes the message,
S
leaves the message unchanged, and
E
leaves the remaining messages unchanged\&.
.sp
.if n \{\
.RS 4
.\}
.nf
mailtool \-filter INBOX pop3://john@mail\&.example\&.com/novalidate\-cert
.fi
.if n \{\
.RE
.\}
.if n \{\
.sp
.\}
.RS 4
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
.ps +1
\fBNote\fR
.ps -1
.br
.PP

\-filter
is not meant to be used with large folders\&. Unless messages are removed quickly, the connection to the server may be disconnected for inactivity\&.
.sp .5v
.RE
.SS "Copying folders"
.HP \w'\fBmailtool\fR\ 'u
\fBmailtool\fR [\-recurse] \-tofolder \fItofolder\fR \-copyto \fItoaccount\fR \-fromfolder \fIfromfolder\fR \fIfromaccount\fR
.PP
This command copies an entire folder,
fromfolder
in
fromaccount
to a new folder,
tofolder
(which will be created, if necessary) in
toaccount\&. Optionally,
\-recurse
specifies that all subfolders of
fromfolder
should also be copied\&.
.sp
.if n \{\
.RS 4
.\}
.nf

mailtool \-tofolder INBOX \-copyto maildir:Maildir \e
    \-fromfolder "INBOX" imap://mbox100@mail\&.example\&.com/novalidate\-cert

mailtool \-recurse \-tofolder INBOX\&.converted_mail \e
    \-copyto maildir:Maildir \-fromfolder "mail" \e
        imap://mbox100@mail\&.example\&.com/novalidate\-cert
.fi
.if n \{\
.RE
.\}
.PP
This example first copies the INBOX on the IMAP server to
$HOME/Maildir, then copies subfolders of
\(lqmail\(rq
on the IMAP server to the
\(lqconverted_mail\(rq
subfolder in the maildir\&.
.sp
.if n \{\
.RS 4
.\}
.nf
mailtool \-tofolder INBOX \-copyto maildir:Maildir \e
   \-fromfolder "INBOX" inbox:mail

mailtool \-recurse \-tofolder INBOX\&.converted_mail \e
    \-copyto maildir:Maildir \-fromfolder "" mbox:mail

.fi
.if n \{\
.RE
.\}
.PP
This example first copies
$HOME/Inbox
(accessed as the INBOX folder in inbox:mail) to
$HOME/Maildir, then copies mbox folders from
$HOME/mail
to the
\(lqconverted_mail\(rq
subfolder in the maildir\&.
.if n \{\
.sp
.\}
.RS 4
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
.ps +1
\fBNote\fR
.ps -1
.br
.PP
Mail accounts that contain hybrid folders (folders that contain both messages and subfolders) can only be copied to account types that also support hybrid folders: either local maildirs, or to remote servers that support hybrid folders\&.
.sp .5v
.RE
.SH "SEE ALSO"
.PP

\fBcone\fR(1)\&.
